### PR TITLE
Add automated testing framework

### PR DESCRIPTION
**Pull request by khale**
This PR adds a testing framework to Nautilus. This makes it *much* easier to test code you've written for some component. The meat of this PR is in 5d23e52. Key features include:

- tests can be added *within* the component you're working on. No need to edit core kernel code. You can see how to use this in the [contrib](https://github.com/HExSA-Lab/nautilus/blob/master/CONTRIBUTING.md) doc (modified in d7ac2c4) and in `src/test/test.c`.
- tests that are added are automatically tied to the kernel command-line processing framework, so can be invoked easily by adding a kernel command-line flag (`-test <testname> "arg1 arg2 arg3"`)
- tests can be integrated with the automated build system (0e19246). This is done using a YAML-formatted test matrix (a4bf0c5). Note that each of these tests can be run for any number of configs. Two default configs are provided in this PR (see 10573b3).

Other changes:
- adc7ce9 allows us to pass in a specific exit code to QEMU when it shuts down. Needed for scripted tests.
- b16fd37 autogenerates an iso directory for each `make isoimage` build. This just cleans up some cruft in the source directory
- e61279a makes build output for `make isoimage` less cluttered.
Note: integration with the shell will be trivial once the shell rewrite PR is merged in.
- d7ac2c4 adds supporting documentation for the testing framework

### CODE REVIEW

**Comment by khale** [comment]
This pull request **introduces 6 alerts** when merging d7ac2c43d7baee2c54847086c2ddc919134fbea7 into 29bf3429c302edc04fd57ab0ef7f4f745295dbd1 - [view on LGTM.com](https://lgtm.com/projects/g/HExSA-Lab/nautilus/rev/pr-fc9a508a26bcb06d6cbbb230e5c1ee9ddc2ce50c)

**new alerts:**

* 4 for Unused local variable
* 1 for Unused import
* 1 for Module is imported with &#39;import&#39; and &#39;import from&#39;

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by khale** [comment]
This pull request **introduces 6 alerts** when merging 5ae719f23b5213473906263ab8178e1de4d1e727 into 29bf3429c302edc04fd57ab0ef7f4f745295dbd1 - [view on LGTM.com](https://lgtm.com/projects/g/HExSA-Lab/nautilus/rev/pr-4ec96873e1b147ae5ce8c3cbf1d844d7742fa530)

**new alerts:**

* 4 for Unused local variable
* 1 for Unused import
* 1 for Module is imported with &#39;import&#39; and &#39;import from&#39;

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by khale** [comment]
This pull request **introduces 6 alerts** when merging e78623c896710797f14ede4ed3e7e2d1323a7bf3 into 29bf3429c302edc04fd57ab0ef7f4f745295dbd1 - [view on LGTM.com](https://lgtm.com/projects/g/HExSA-Lab/nautilus/rev/pr-4662cb68eead12121fae53a528db817b5fa774d2)

**new alerts:**

* 4 for Unused local variable
* 1 for Unused import
* 1 for Module is imported with &#39;import&#39; and &#39;import from&#39;

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Review by PeterDinda — APPROVED** [review]
Looks pretty cool.   I have no objections, but do have the following comments:

- I'm assuming that this doesn't affect the existing tests (and doesn't incorporate them either)

- It looks like the test framework starts in init, which might potentially be a bad idea.    I realize it is very late in the boot process, but perhaps it would make more sense to start it as an autoexec script in the shell, just so you can be sure that we are all up and functional in a child thread.

- It would be cool if tests *could* be run from the shell.  Basically some shell command like "test framework <kernel command line>" that launches it.   

- Does the testing framework provide timeouts?  Is there a way I can write a test that says "this will take at most 1 minute.   If it takes longer, it's probably hung and so declare it a failure"

- Perhaps add the relevant changes to other linker scripts and other init.cs?

**Comment by khale** [comment]
@PeterDinda thanks for the feedback. 

- existing tests are not incorporated, although I will be incorporating some that I'm in charge of (specifically Nemo related)
- did not consider the child thread issue, will consider autoexec, or potentially the constraint that all tests are run in a newly spawned thread
- the shell invocation for tests is my next planned addition for this---was waiting on the shell rewrite to go in first
- no timeouts, but that's a good idea---presumably easier now with the revamped timer framework
- other linker/init integration is also in the works, but is on hold until deadline season passes

**Comment by khale** [comment]
This pull request **introduces 6 alerts** when merging e6d9b191b1b2d251e238c588b12f8146950e0878 into 189083de8cf5cea7eabdf61ae8a472ab3316503c - [view on LGTM.com](https://lgtm.com/projects/g/HExSA-Lab/nautilus/rev/pr-1b9fde2805e983a2f1f8ab60564f01aa511e76b5)

**new alerts:**

* 4 for Unused local variable
* 1 for Unused import
* 1 for Module is imported with &#39;import&#39; and &#39;import from&#39;

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by khale** [comment]
This pull request **introduces 6 alerts** when merging f2c7ce092f3b0e6dbd640056feb5b9ee95679da9 into 189083de8cf5cea7eabdf61ae8a472ab3316503c - [view on LGTM.com](https://lgtm.com/projects/g/HExSA-Lab/nautilus/rev/pr-58768ea5e9e6deb1e1e7fc64c7c797c5bfd6bfc2)

**new alerts:**

* 4 for Unused local variable
* 1 for Unused import
* 1 for Module is imported with &#39;import&#39; and &#39;import from&#39;

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Pull request merged**
